### ISSUE TITLE
File caching proposal

### ISSUE THREAD

**Issue by SoftwareGuy** [KanColleTool/KanColleTool#119]
Just thinking how we could implement a cache system. Yes, we shouldn't cache the SWFs because the cache could be come corrupt or stale and cause version mismatches, but here's what I propose:

**When the viewer is going to load a file, intercept the request.**
- Stage 1: Fire a request to DMM Server for the length/date modified.
- Stage 2: Check file modification date against our local copy.
  - If file is newer on server than our local disk copy, then fetch. Overwrite existing one.
  - If file exists but doesn't match the server (ie. broken download, etc), then fetch.
  - If file doesn't exist on local disk, then fetch.
- Stage 3: Return the file data (either from the disk or HTTP request) to game.
- Stage 4: ???
- Stage 5: Profit

**Benefits**
- Fast loading times. We are not redownloading the files every time.
  - Bandwidth deduction for those on quota'd connections (thanks Australia).
  - Reduces amount of black screen and/or glitched screens (ie. Sortie screen getting FUBAR with the admiral office screen (main game scene thing). Happens.)

**Downsides**
- Cache may become corrupt if viruses or other malicious software infect the files inside the cache.
- Cache may become stale if update is released.
  - A workaround would be to bomb the cache every X days (user configurable?)

Another take on this idea is to cache only sounds, music and shipgirl graphic SWFs, but leave the SWF for the scenes on the server. This would save a lot of "empty" slots when the game hasn't got what it wants in time and KCT is busy pulling all the resources from the slow server.

I'm sure we can come up with something, its just a matter of putting heads together and tossing a few ideas around.

**Comment by uppfinnarn** [comment]
[I'm pretty sure this is already happening?](https://github.com/KanColleTool/kct-viewer/blob/master/src/KVMainWindow.cpp#L49)

If it's not working to a satisfactory degree though, reimplementing [QAbstractNetworkCache](http://doc.qt.io/qt-5/qabstractnetworkcache.html) to provide more aggressive/selective caching could be a good idea. It doesn't look too hard either.

**Comment by SoftwareGuy** [comment]
Can't confirm the caching is happening, when I logged into KC today it wanted to download all the assets (rather than just blitzing through the loading bar). I'll see if it sticks tomorrow, otherwise could an "expiry" HTTP header be expiring the files?

**Comment by uppfinnarn** [comment]
Ah, of course, that cache assumes proper caching headers on the remote resources, which they would of course not send out >.>;;

Reimplementing the cache sounds very tempting, and it seems like a better solution than trying to inject HTTP headers into responses.

**Comment by SunDwarf** [comment]
What headers? The official severs send a Content-Type header, an
X-Powered-By header, and.... that's it.

Caching would probably be impossible without anything to say what the file
is like before its downloaded.

**Comment by uppfinnarn** [comment]
DMM in charge of running servers (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

What we could do is just, checksum mainD2.swf and clear the cache if that changes. That should invalidate the cache for every patch, as mainD2.swf contains rotating keys for requesting port2.json.

**Comment by SunDwarf** [comment]
I can't check this as my PC is 150 miles away, but do the older versions of
the files (?VERSION=) successfully download? I mean KC being KC it might
just return 200 but with their shitty api response, or it might return 403,
meaning it needs to invalidate the cache.

**Comment by uppfinnarn** [comment]
I *think* that's a cache buster, actually, now that you mention it… I can't verify it right now, but I can in a while, if nobody else does it first.

**Comment by uppfinnarn** [comment]
Interestingly, it seems to respect `If-Modified-Since` and properly returns HTTP 304s.

**Comment by uppfinnarn** [comment]
Yup, cache buster! At least for Core.swf, the latest version and a gibberish version have identical checksums. We can use this.

**Comment by SoftwareGuy** [comment]
So you're saying that the gibberish is what causes KCT to bust the cache and redownload the assets everytime? If we just chop the `?VERSION=` part off the request, it should be OK, no?

Or am I reading this wrong?

**Comment by uppfinnarn** [comment]
No, a cache buster is the exact opposite - it's a string tucked onto the end of the URL of a static asset, by an uncacheable one with knowledge of various files' versioning, to force a cached asset to be redownloaded.

Let's say you have a webapp. Since it's 2015, you naturally have an asset pipeline of some kind - compiling LESS/SASS sources into CSS, combining and minifying JS files, etc. into a small number of compressed files. Let's call them `style.css` and `script.js`.

Because you want the app to load quickly, you specify that these assets can be cached for a very long time, so that your server doesn't even have to be asked if `style.css` and `script.js` has changed every time the site loads. This way, the only additional requests that will occur when your site loads are for images.

However, sometimes you'll want to change these assets. Maybe you retheme the site, add some new scripts, or update something. Your users will now see up-to-date HTML, but outdated CSS+JS!

The solution to this is called a "cache buster". By adding something like "?ver=2" to the end of these URLs, the browser will see two different files:

* http://example.com/assets/style.css?ver=1
* http://example.com/assets/style.css?ver=2

Thus, in the browser's eyes, you may or may not be requesting a completely different file, and the cache for the old version won't apply. In a real web application, you'd typically use a hash of the file - I'm not sure what KanColle uses, but it's definitely a cache buster.

(Now, they're not actually sending cache headers properly, but we can work around that. Because we know they use cache busters, we can aggressively cache all versioned assets!)

**Comment by SoftwareGuy** [comment]
OK, so we aggressively cache the versioned assets... So then we'll just load from disk instead of querying the server every request for SWF files? By that, I mean:

* KCT is about to load "PortMain.swf?ver=9001"
* KCT knows we cached that before
* KCT jumps the shark and passes the game the cached copy of that file since it knows it's the correct one thus saving download time from DMM servers
* Game is happy chappy and continues blowing up your fleet

Or am I still looking in the wrong direction?

**Comment by SunDwarf** [comment]
Good luck tricking the game into loading said files.

**Comment by uppfinnarn** [comment]
We control the entire network stack already (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

I also just tested and the normal cache it's using now seems to cache everything just fine for me, doesn't it for you?

**Comment by SunDwarf** [comment]
Confession: I've never used KCT. My personal experience with this was
trying to get the client to download files from DMM using 302s, which
unsurprisingly didn't work

**Comment by SoftwareGuy** [comment]
Do you want me to test, @uppfinnarn ?

**Comment by uppfinnarn** [comment]
It should be working already, but please do.

**Comment by SoftwareGuy** [comment]
Okay, I tested it and it seems that the cache is working for the main SWF and the core and portmain. Any other scenes just errorcat, which is weird. 0.9.4 on Windows (my build that you released) doesn't do that, but on my Linux Mint it does. WTH?

**Comment by SunDwarf** [comment]
As of today, (at least the one I play on) DMM servers are now sending proper cache headers?

```
HTTP/1.1 200 OK
Date: Sat, 08 Aug 2015 10:02:16 GMT
Server: Apache
Last-Modified: Fri, 12 Jun 2015 06:55:37 GMT
Accept-Ranges: bytes
Content-Length: 1228724
Cache-Control: max-age=2592000, public
Connection: close
Content-Type: application/x-shockwave-flash
```

**Comment by uppfinnarn** [comment]
Closing this because it seems to be working already.
